openapi: 3.0.0
servers:
  - url: https://api.hr-leave.com
info:
  title: HR Leave API
  description: Provides employee leave information.
  version: "1.0"

paths:
  /v1/leave:
    get:
      operationId: getLeaveStatus
      summary: Current leave status for an employee
      description: Returns current leave balance and latest leave request status.
      parameters:
        - name: employee_id
          in: query
          required: true
          schema:
            type: string
          description: Employee identifier

      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  employee_id:
                    type: string
                    example: emp001
                  annual_leave_balance:
                    type: integer
                    example: 12
                  sick_leave_balance:
                    type: integer
                    example: 8
                  latest_leave_status:
                    type: string
                    example: APPROVED
                  last_updated:
                    type: string
                    example: "2026-01-28T15:00:00Z"

        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    example: true
                  reason:
                    type: string
                    example: "Employee ID is required"
